-- =====================================================================
-- 동행 소통 및 안전 (REQ-F-508 ~ 513, REQ-N-023)
-- =====================================================================

-- 모집글 공개 문의 댓글 (REQ-F-510)
CREATE TABLE companion_comments (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    companion_post_id BIGINT NOT NULL REFERENCES companion_posts(id),
    user_id           BIGINT NOT NULL REFERENCES users(id),
    content           VARCHAR(500) NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at        TIMESTAMPTZ
);
CREATE INDEX idx_comment_post ON companion_comments (companion_post_id, created_at);
COMMENT ON TABLE companion_comments IS 'REQ-F-510 지원 전 문의용 공개 댓글';

-- 확정자 전용 대화 (REQ-F-511)
-- 모집 글 1건에 대화방이 정확히 1개 대응하므로 별도 room 테이블을 두지 않는다.
CREATE TABLE companion_messages (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    companion_post_id BIGINT NOT NULL REFERENCES companion_posts(id),
    user_id           BIGINT NOT NULL REFERENCES users(id),
    content           VARCHAR(1000) NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_message_post ON companion_messages (companion_post_id, created_at);
COMMENT ON TABLE companion_messages IS 'REQ-F-511. REQ-N-023 에 따라 경기 종료 후 90일 보존';

-- 읽음 처리 (메시지마다 행을 쌓지 않고 마지막 읽은 시각만 보관)
CREATE TABLE companion_message_reads (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    companion_post_id BIGINT NOT NULL REFERENCES companion_posts(id),
    user_id           BIGINT NOT NULL REFERENCES users(id),
    last_read_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_read_post_user UNIQUE (companion_post_id, user_id)
);

-- 신고 (REQ-F-508)
CREATE TABLE reports (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id BIGINT NOT NULL REFERENCES users(id),
    target_type VARCHAR(20) NOT NULL CHECK (target_type IN ('POST','COMMENT','MESSAGE','USER')),
    target_id   BIGINT NOT NULL,
    reason      VARCHAR(255) NOT NULL,
    status      VARCHAR(20) NOT NULL DEFAULT 'PENDING'
                CHECK (status IN ('PENDING','REVIEWED','DISMISSED')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    reviewed_at TIMESTAMPTZ,
    reviewed_by BIGINT REFERENCES users(id),
    CONSTRAINT uk_report_target UNIQUE (reporter_id, target_type, target_id)
);
CREATE INDEX idx_report_target ON reports (target_type, target_id);
CREATE INDEX idx_report_status ON reports (status, created_at);
COMMENT ON TABLE reports IS 'REQ-F-508. 대상마다 테이블을 나누지 않고 target_type + target_id 로 통합한다';

-- 사용자 차단 (REQ-F-509)
CREATE TABLE user_blocks (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id),
    blocked_id BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_block UNIQUE (user_id, blocked_id),
    CONSTRAINT ck_block_not_self CHECK (user_id <> blocked_id)
);
